#!/bin/env python3
# Config file for Run3 sample postprocessing
# File automatically generated by create_cfg.py script on 2023-12-02 [yyyy-mm-dd] -- EDIT AT YOUR OWN RISK
from CMGTools.RootTools.samples.ComponentCreator import ComponentCreator
import os
kreator = ComponentCreator()
# ------ Group: WZ
#  + Process: WZto3LNu 
WZto3LNu_pow = kreator.makeMCComponentFromLocal("WZto3LNu_pow", "", "/lustrefs/hdd_pool_dir/nanoAODv12/16dec2023_noSkimWZ/WZsignalSamples_Run3Summer22EE/WZto3LNu_TuneCP5_13p6TeV_powheg-pythia8/unskimSignal_WZto3LNu_TuneCP5_13p6TeV_powheg-pythia8/231215_143545/0000", ".*root", 5.31)
WZ_pow = [WZto3LNu_pow]

WZto3LNu_amc = kreator.makeMCComponentFromLocal("WZto3LNu_amc", "", "/lustrefs/hdd_pool_dir/nanoAODv12/16dec2023_noSkimWZ/WZsignalSamples_Run3Summer22EE/WZto3LNu-1Jets-4FS_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/unskimSignal_WZto3LNu-1Jets-4FS_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/231215_143726/0000/", ".*root", 5.31)
WZ_amc = [WZto3LNu_amc]

mcSamples_list = WZ_pow + WZ_amc
mcSamples_toImport = mcSamples_list