#!/bin/env python3
# Config file for Run3 sample postprocessing
# File automatically generated by create_cfg.py script on 2023-09-30 [yyyy-mm-dd] -- EDIT AT YOUR OWN RISK
from CMGTools.RootTools.samples.ComponentCreator import ComponentCreator
import os
kreator = ComponentCreator()
# ------ prompt_WZ dataset
WZto3LNu_0 = kreator.makeMCComponentFromLocal("WZto3LNu", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/MC/2022PostEE/WZto3LNu_TuneCP5_13p6TeV_powheg-pythia8/mcRun3_PostEE_april2023_WZto3LNu_TuneCP5_13p6TeV_powheg-pythia8/230711_162907/0000", ".*root", 5.31)
prompt_WZ = [WZto3LNu_0]

# ------ prompt_ZZ dataset
ZZto4l_0 = kreator.makeMCComponentFromLocal("ZZto4l", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/MC/2022PostEE/ZZto4L_TuneCP5_13p6TeV_powheg-pythia8/mcRun3_PostEE_april2023_ZZto4L_TuneCP5_13p6TeV_powheg-pythia8/230626_145402/0000", ".*root", 1.65)
prompt_ZZ = [ZZto4l_0]

# ------ prompt_VVV dataset
WWZ_0 = kreator.makeMCComponentFromLocal("WWZ", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/MC/2022PostEE/WWZ_4F_TuneCP5_13p6TeV_amcatnlo-pythia8/mcRun3_PostEE_april2023_WWZ_4F_TuneCP5_13p6TeV_amcatnlo-pythia8/230614_144831/0000", ".*root", 0.1851)
WZZ_0 = kreator.makeMCComponentFromLocal("WZZ", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/MC/2022PostEE/WZZ_TuneCP5_13p6TeV_amcatnlo-pythia8/mcRun3_PostEE_april2023_WZZ_TuneCP5_13p6TeV_amcatnlo-pythia8/230614_145019/0000", ".*root", 0.06206)
ZZZ_0 = kreator.makeMCComponentFromLocal("ZZZ", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/MC/2022PostEE/ZZZ_TuneCP5_13p6TeV_amcatnlo-pythia8/mcRun3_PostEE_april2023_ZZZ_TuneCP5_13p6TeV_amcatnlo-pythia8/230614_144308/0000", ".*root", 0.01591)
prompt_VVV = [WWZ_0, WZZ_0, ZZZ_0]

# ------ prompt_hZZ dataset
ggHtoZZto4L_0 = kreator.makeMCComponentFromLocal("ggHtoZZto4L", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/MC/2022PostEE/GluGluHtoZZto4L_M-125_TuneCP5_13p6TeV_powheg2-JHUGenV752-pythia8/mcRun3_PostEE_april2023_GluGluHtoZZto4L_M-125_TuneCP5_13p6TeV_powheg2-JHUGenV752-pythia8/230614_144644/0000", ".*root", 0.012)
prompt_hZZ = [ggHtoZZto4L_0]

# ------ prompt_TTX dataset
TTLL_MLL_50_0 = kreator.makeMCComponentFromLocal("TTLL_MLL_50", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/MC/2022PostEE/TTLL_MLL-50_TuneCP5_13p6TeV_amcatnlo-pythia8/mcRun3_PostEE_april2023_TTLL_MLL-50_TuneCP5_13p6TeV_amcatnlo-pythia8/230908_090345/0000", ".*root", 0.08646)
TTLL_MLL_4to50_0 = kreator.makeMCComponentFromLocal("TTLL_MLL_4to50", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/MC/2022PostEE/TTLL_MLL-4to50_TuneCP5_13p6TeV_amcatnlo-pythia8/mcRun3_PostEE_april2023_TTLL_MLL-4to50_TuneCP5_13p6TeV_amcatnlo-pythia8/230908_090531/0000", ".*root", 0.03949)
prompt_TTX = [TTLL_MLL_50_0, TTLL_MLL_4to50_0]

# ------ fakes_VV dataset
ZZto2L2Q_0 = kreator.makeMCComponentFromLocal("ZZto2L2Q", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/MC/2022PostEE/ZZto2L2Q_TuneCP5_13p6TeV_powheg-pythia8/mcRun3_PostEE_april2023_ZZto2L2Q_TuneCP5_13p6TeV_powheg-pythia8/230626_145036/0000", ".*root", 8.08)
ZZto2L2Nu_0 = kreator.makeMCComponentFromLocal("ZZto2L2Nu", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/MC/2022PostEE/ZZto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/mcRun3_PostEE_april2023_ZZto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/230626_144856/0000", ".*root", 1.19)
WWto2L2Nu_0 = kreator.makeMCComponentFromLocal("WWto2L2Nu", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/MC/2022PostEE/WWto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/mcRun3_PostEE_april2023_WWto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/230908_090003/0000", ".*root", 12.98)
fakes_VV = [ZZto2L2Q_0, ZZto2L2Nu_0, WWto2L2Nu_0]

# ------ fakes_TT dataset
TTTo2L2Nu_0 = kreator.makeMCComponentFromLocal("TTTo2L2Nu", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/MC/2022PostEE/TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/mcRun3_PostEE_april2023_TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/230404_141055/0000", ".*root", 97.4488)
fakes_TT = [TTTo2L2Nu_0]

# ------ fakes_DY dataset
DYJetsToLL_M50_0 = kreator.makeMCComponentFromLocal("DYJetsToLL_M50", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/MC/2022PostEE/DYto2L-2Jets_MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/mcRun3_PostEE_april2023_DYto2L-2Jets_MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/230404_142241/0000", ".*root", 6345.99)
DYJetsToLL_M10to50_0 = kreator.makeMCComponentFromLocal("DYJetsToLL_M10to50", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/MC/2022PostEE/DYto2L-2Jets_MLL-10to50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/mcRun3_PostEE_april2023_DYto2L-2Jets_MLL-10to50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/230404_142007/0000", ".*root", 19982.5)
fakes_DY = [DYJetsToLL_M50_0, DYJetsToLL_M10to50_0]

# ------ fakes_T dataset
TWminus_0 = kreator.makeMCComponentFromLocal("TWminus", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/MC/2022PostEE/TWminus_DR_AtLeastOneLepton_TuneCP5_13p6TeV_powheg-pythia8/mcRun3_PostEE_april2023_TWminus_DR_AtLeastOneLepton_TuneCP5_13p6TeV_powheg-pythia8/230404_141347/0000", ".*root", 23.8979)
TbarWplus_0 = kreator.makeMCComponentFromLocal("TbarWplus", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/MC/2022PostEE/TbarWplus_DR_AtLeastOneLepton_TuneCP5_13p6TeV_powheg-pythia8/mcRun3_PostEE_april2023_TbarWplus_DR_AtLeastOneLepton_TuneCP5_13p6TeV_powheg-pythia8/230404_141710/0000", ".*root", 23.8979)
fakes_T = [TWminus_0, TbarWplus_0]

# ------ fakes_V dataset
WtoLnu_2jets_0 = kreator.makeMCComponentFromLocal("WtoLnu_2jets", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/MC/2022PostEE/WtoLNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/mcRun3_PostEE_april2023_WtoLNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/230712_152849/0000", ".*root", 64481.58)
fakes_V = [WtoLnu_2jets_0]

# ------ convs dataset
WZG_0 = kreator.makeMCComponentFromLocal("WZG", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/MC/2022PostEE/WZGtoLNuZG_TuneCP5_13p6TeV_amcatnlo-pythia8/mcRun3_PostEE_april2023_WZGtoLNuZG_TuneCP5_13p6TeV_amcatnlo-pythia8/230614_144456/0000", ".*root", 0.08425)
convs = [WZG_0]




mcSamples_list = prompt_WZ + prompt_ZZ + prompt_VVV + prompt_hZZ + prompt_TTX + fakes_VV + fakes_TT + fakes_DY + fakes_T + fakes_V + convs
mcSamples_toImport = mcSamples_list