#!/bin/env python3
# Config file for Run3 sample postprocessing
# File automatically generated by create_cfg.py script on 2023-12-02 [yyyy-mm-dd] -- EDIT AT YOUR OWN RISK
from CMGTools.RootTools.samples.ComponentCreator import ComponentCreator
import os
kreator = ComponentCreator()
json = os.environ["CMSSW_BASE"]+"/src/CMGTools/TTHAnalysis/cfg/Cert_Collisions2022_355100_362760_Golden.json"
# ------ Group: data
#  + Process: Muon_Run2022F 
Muon_Run2022F_0 = kreator.makeDataComponentFromLocal("Muon_Run2022F", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/data/2022PostEE/Muon/dataRun3_PostEE_oct2023_frmeasurement_muon_Muon_Run2022F-22Sep2023-v2/231130_114432/0000", "", ".*root", "2022EE", [], json = json)
data = [Muon_Run2022F_0]




dataSamples_list = data
dataSamples_toImport = dataSamples_list