#!/bin/env python3
# Config file for Run3 sample postprocessing
# File automatically generated by create_cfg.py script on 2023-09-30 [yyyy-mm-dd] -- EDIT AT YOUR OWN RISK
from CMGTools.RootTools.samples.ComponentCreator import ComponentCreator
import os
kreator = ComponentCreator()
json = os.environ["CMSSW_BASE"]+"/src/CMGTools/TTHAnalysis/cfg/Cert_Collisions2022_355100_362760_Golden.json"
# ------ Egamma dataset
EGamma_Run2022F_0 = kreator.makeDataComponentFromLocal("EGamma_Run2022F", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/data/2022PostEE/EGamma/dataRun3_PostEE_april2023_EGamma_Run2022F-PromptNanoAODv11_v1-v2/230404_162103/0000", "", ".*root", "2022EE", [], json = json)
EGamma_Run2022G_0 = kreator.makeDataComponentFromLocal("EGamma_Run2022G", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/data/2022PostEE/EGamma/dataRun3_PostEE_april2023_EGamma_Run2022G-PromptNanoAODv11_v1-v2/230404_162325/0000", "", ".*root", "2022EE", [], json = json)
Egamma = [EGamma_Run2022F_0, EGamma_Run2022G_0]

# ------ Muon dataset
Muon_Run2022F_0 = kreator.makeDataComponentFromLocal("Muon_Run2022F", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/data/2022PostEE/Muon/dataRun3_PostEE_april2023_Muon_Run2022F-PromptNanoAODv11_v1-v2/230404_161330/0000", "", ".*root", "2022EE", [], json = json)
Muon_Run2022G_0 = kreator.makeDataComponentFromLocal("Muon_Run2022G", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/data/2022PostEE/Muon/dataRun3_PostEE_april2023_Muon_Run2022G-PromptNanoAODv11_v1-v2/230404_161607/0000", "", ".*root", "2022EE", [], json = json)
Muon = [Muon_Run2022F_0, Muon_Run2022G_0]

# ------ MuonEG dataset
MuonEG_Run2022F_0 = kreator.makeDataComponentFromLocal("MuonEG_Run2022F", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/data/2022PostEE/MuonEG/dataRun3_PostEE_april2023_MuonEG_Run2022F-PromptNanoAODv11_v1-v2/230516_163344/0000", "", ".*root", "2022EE", [], json = json)
MuonEG_Run2022G_0 = kreator.makeDataComponentFromLocal("MuonEG_Run2022G", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/data/2022PostEE/MuonEG/dataRun3_PostEE_april2023_MuonEG_Run2022G-PromptNanoAODv11_v1-v2/230404_161836/0000", "", ".*root", "2022EE", [], json = json)
MuonEG = [MuonEG_Run2022F_0, MuonEG_Run2022G_0]

# ------ JetMET dataset
JetMET_Run2022F_0 = kreator.makeDataComponentFromLocal("JetMET_Run2022F", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/data/2022PostEE/JetMET/dataRun3_PostEE_april2023_JetMET_Run2022F-PromptNanoAODv11_v1-v2/230516_163551/0000", "", ".*root", "2022EE", [], json = json)
JetMET_Run2022G_0 = kreator.makeDataComponentFromLocal("JetMET_Run2022G", "", "/lustrefs/hdd_pool_dir/nanoAODv11/30march2023/data/2022PostEE/JetMET/dataRun3_PostEE_april2023_JetMET_Run2022G-PromptNanoAODv11_v1-v2/230516_163734/0000", "", ".*root", "2022EE", [], json = json)
JetMET = [JetMET_Run2022F_0, JetMET_Run2022G_0]




dataSamples_list = Egamma + Muon + MuonEG + JetMET
dataSamples_toImport = dataSamples_list