#!/bin/env python3
# Config file for Run3 sample postprocessing
# File automatically generated by create_cfg.py script on 2023-12-02 [yyyy-mm-dd] -- EDIT AT YOUR OWN RISK
from CMGTools.RootTools.samples.ComponentCreator import ComponentCreator
import os
kreator = ComponentCreator()
# ------ Group: qcd
#  + Process: QCD_PT_10to30_EMEnriched 
QCD_PT_10to30_EMEnriched_0 = kreator.makeMCComponentFromLocal("QCD_PT_10to30_EMEnriched", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-10to30_EMEnriched_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-10to30_EMEnriched_TuneCP5_13p6TeV_pythia8/231029_070758/0000", ".*root", 1)
#  + Process: QCD_PT_30to50_EMEnriched 
QCD_PT_30to50_EMEnriched_0 = kreator.makeMCComponentFromLocal("QCD_PT_30to50_EMEnriched", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-30to50_EMEnriched_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-30to50_EMEnriched_TuneCP5_13p6TeV_pythia8/231029_071240/0000", ".*root", 1)
#  + Process: QCD_PT_50to80_EMEnriched 
QCD_PT_50to80_EMEnriched_0 = kreator.makeMCComponentFromLocal("QCD_PT_50to80_EMEnriched", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-50to80_EMEnriched_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-50to80_EMEnriched_TuneCP5_13p6TeV_pythia8/231029_071413/0000", ".*root", 1)
#  + Process: QCD_PT_80to120_EMEnriched 
QCD_PT_80to120_EMEnriched_0 = kreator.makeMCComponentFromLocal("QCD_PT_80to120_EMEnriched", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-80to120_EMEnriched_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-80to120_EMEnriched_TuneCP5_13p6TeV_pythia8/231029_071547/0000", ".*root", 1)
#  + Process: QCD_PT_120to170_EMEnriched 
QCD_PT_120to170_EMEnriched_0 = kreator.makeMCComponentFromLocal("QCD_PT_120to170_EMEnriched", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-120to170_EMEnriched_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-120to170_EMEnriched_TuneCP5_13p6TeV_pythia8/231029_070932/0000", ".*root", 1)
#  + Process: QCD_PT_170to300_EMEnriched 
QCD_PT_170to300_EMEnriched_0 = kreator.makeMCComponentFromLocal("QCD_PT_170to300_EMEnriched", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-170to300_EMEnriched_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-170to300_EMEnriched_TuneCP5_13p6TeV_pythia8/231119_221846/0000", ".*root", 1)
#  + Process: QCD_PT_300_EMEnriched 
QCD_PT_300_EMEnriched_0 = kreator.makeMCComponentFromLocal("QCD_PT_300_EMEnriched", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-300_EMEnriched_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-300_EMEnriched_TuneCP5_13p6TeV_pythia8/231029_071105/0000", ".*root", 1)
#  + Process: QCD_PT_15to20_MuEnrichedPt5 
QCD_PT_15to20_MuEnrichedPt5_0 = kreator.makeMCComponentFromLocal("QCD_PT_15to20_MuEnrichedPt5", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-15to20_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-15to20_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/231027_164937/0000", ".*root", 1)
#  + Process: QCD_PT_20to30_MuEnrichedPt5 
QCD_PT_20to30_MuEnrichedPt5_0 = kreator.makeMCComponentFromLocal("QCD_PT_20to30_MuEnrichedPt5", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-20to30_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-20to30_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/231027_165112/0000", ".*root", 1)
#  + Process: QCD_PT_30to50_MuEnrichedPt5 
QCD_PT_30to50_MuEnrichedPt5_0 = kreator.makeMCComponentFromLocal("QCD_PT_30to50_MuEnrichedPt5", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-30to50_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-30to50_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/231027_165424/0000", ".*root", 1)
#  + Process: QCD_PT_50to80_MuEnrichedPt5 
QCD_PT_50to80_MuEnrichedPt5_0 = kreator.makeMCComponentFromLocal("QCD_PT_50to80_MuEnrichedPt5", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-50to80_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-50to80_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/231027_165739/0000", ".*root", 1)
#  + Process: QCD_PT_80to120_MuEnrichedPt5 
QCD_PT_80to120_MuEnrichedPt5_0 = kreator.makeMCComponentFromLocal("QCD_PT_80to120_MuEnrichedPt5", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-80to120_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-80to120_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/231119_220305/0000", ".*root", 1)
#  + Process: QCD_PT_120to170_MuEnrichedPt5 
QCD_PT_120to170_MuEnrichedPt5_0 = kreator.makeMCComponentFromLocal("QCD_PT_120to170_MuEnrichedPt5", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-120to170_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-120to170_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/231027_164801/0000", ".*root", 1)
#  + Process: QCD_PT_170to300_MuEnrichedPt5 
#  + Process: QCD_PT_300to470_MuEnrichedPt5 
QCD_PT_300to470_MuEnrichedPt5_0 = kreator.makeMCComponentFromLocal("QCD_PT_300to470_MuEnrichedPt5", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-300to470_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-300to470_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/231027_165249/0000", ".*root", 1)
#  + Process: QCD_PT_470to600_MuEnrichedPt5 
QCD_PT_470to600_MuEnrichedPt5_0 = kreator.makeMCComponentFromLocal("QCD_PT_470to600_MuEnrichedPt5", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-470to600_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-470to600_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/231027_165600/0000", ".*root", 1)
#  + Process: QCD_PT_600to800_MuEnrichedPt5 
QCD_PT_600to800_MuEnrichedPt5_0 = kreator.makeMCComponentFromLocal("QCD_PT_600to800_MuEnrichedPt5", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-600to800_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-600to800_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/231027_165915/0000", ".*root", 1)
#  + Process: QCD_PT_800to1000_MuEnrichedPt5 
QCD_PT_800to1000_MuEnrichedPt5_0 = kreator.makeMCComponentFromLocal("QCD_PT_800to1000_MuEnrichedPt5", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-800to1000_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-800to1000_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/231027_170052/0000", ".*root", 1)
#  + Process: QCD_PT_1000_MuEnrichedPt5 
QCD_PT_1000_MuEnrichedPt5_0 = kreator.makeMCComponentFromLocal("QCD_PT_1000_MuEnrichedPt5", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-1000_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-1000_MuEnrichedPt5_TuneCP5_13p6TeV_pythia8/231027_164619/0000", ".*root", 1)
#  + Process: QCD_PT_20to30_bcToE 
QCD_PT_20to30_bcToE_0 = kreator.makeMCComponentFromLocal("QCD_PT_20to30_bcToE", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-20to30_bcToE_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-20to30_bcToE_TuneCP5_13p6TeV_pythia8/231030_083324/0000", ".*root", 1)
#  + Process: QCD_PT_30to80_bcToE 
QCD_PT_30to80_bcToE_0 = kreator.makeMCComponentFromLocal("QCD_PT_30to80_bcToE", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-30to80_bcToE_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-30to80_bcToE_TuneCP5_13p6TeV_pythia8/231030_083751/0000", ".*root", 1)
#  + Process: QCD_PT_80to170_bcToE 
QCD_PT_80to170_bcToE_0 = kreator.makeMCComponentFromLocal("QCD_PT_80to170_bcToE", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-80to170_bcToE_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-80to170_bcToE_TuneCP5_13p6TeV_pythia8/231119_220916/0000", ".*root", 1)
#  + Process: QCD_PT_170to250_bcToE 
QCD_PT_170to250_bcToE_0 = kreator.makeMCComponentFromLocal("QCD_PT_170to250_bcToE", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-170to250_bcToE_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-170to250_bcToE_TuneCP5_13p6TeV_pythia8/231030_083055/0000", ".*root", 1)
#  + Process: QCD_PT_250_bcToE 
QCD_PT_250_bcToE_0 = kreator.makeMCComponentFromLocal("QCD_PT_250_bcToE", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/QCD_PT-250_bcToE_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_oct2023_QCD_PT-250_bcToE_TuneCP5_13p6TeV_pythia8/231030_083532/0000", ".*root", 1)
qcd = [QCD_PT_10to30_EMEnriched_0, QCD_PT_30to50_EMEnriched_0, QCD_PT_50to80_EMEnriched_0, QCD_PT_80to120_EMEnriched_0, QCD_PT_120to170_EMEnriched_0, QCD_PT_170to300_EMEnriched_0, QCD_PT_300_EMEnriched_0, QCD_PT_15to20_MuEnrichedPt5_0, QCD_PT_20to30_MuEnrichedPt5_0, QCD_PT_30to50_MuEnrichedPt5_0, QCD_PT_50to80_MuEnrichedPt5_0, QCD_PT_80to120_MuEnrichedPt5_0, QCD_PT_120to170_MuEnrichedPt5_0, QCD_PT_300to470_MuEnrichedPt5_0, QCD_PT_470to600_MuEnrichedPt5_0, QCD_PT_600to800_MuEnrichedPt5_0, QCD_PT_800to1000_MuEnrichedPt5_0, QCD_PT_1000_MuEnrichedPt5_0, QCD_PT_20to30_bcToE_0, QCD_PT_30to80_bcToE_0, QCD_PT_80to170_bcToE_0, QCD_PT_170to250_bcToE_0, QCD_PT_250_bcToE_0]

# ------ Group: ewk
#  + Process: ZZto2L2Q 
ZZto2L2Q_0 = kreator.makeMCComponentFromLocal("ZZto2L2Q", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/ZZto2L2Q_TuneCP5_13p6TeV_powheg-pythia8/mcRun3_PostEE_oct2023_ZZto2L2Q_TuneCP5_13p6TeV_powheg-pythia8/231111_115357/0000", ".*root", 8.08)
#  + Process: ZZto2L2Nu 
ZZto2L2Nu_0 = kreator.makeMCComponentFromLocal("ZZto2L2Nu", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/ZZto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/mcRun3_PostEE_oct2023_ZZto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/231110_164134/0000", ".*root", 1.19)
#  + Process: WWto2L2Nu 
WWto2L2Nu_0 = kreator.makeMCComponentFromLocal("WWto2L2Nu", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/WWto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/mcRun3_PostEE_oct2023_WWto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/231111_115713/0000", ".*root", 12.98)
#  + Process: DYto2L_2Jets_MLL_50 
DYto2L_2Jets_MLL_50_0 = kreator.makeMCComponentFromLocal("DYto2L_2Jets_MLL_50", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/DYto2L-2Jets_MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/mcRun3_PostEE_oct2023_DYto2L-2Jets_MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/231111_115216/0000", ".*root", 6345.99)
#  + Process: DYto2L_2Jets_MLL_10to50 
#  + Process: WtoLNu_2Jets 
WtoLNu_2Jets_0 = kreator.makeMCComponentFromLocal("WtoLNu_2Jets", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/WtoLNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/mcRun3_PostEE_oct2023_WtoLNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/231110_163911/0000", ".*root", 64481.58)
ewk = [ZZto2L2Q_0, ZZto2L2Nu_0, WWto2L2Nu_0, DYto2L_2Jets_MLL_50_0, WtoLNu_2Jets_0]

# ------ Group: top
#  + Process: TTtoLNu2Q 
TTtoLNu2Q_0 = kreator.makeMCComponentFromLocal("TTtoLNu2Q", "", "/lustrefs/hdd_pool_dir/nanoAODv12/27oct2023_noSkimForFR/MC/2022PostEE/TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/mcRun3_PostEE_oct2023_TTtoLNu2Q_TuneCP5_13p6TeV_powheg-pythia8/231119_122727/0000", ".*root", 403.25)
top = [TTtoLNu2Q_0]




mcSamples_list = qcd + ewk + top
mcSamples_toImport = mcSamples_list