#!/bin/env python3
# Config file for Run3 sample postprocessing
# File automatically generated by create_cfg.py script on 2023-08-25 [yyyy-mm-dd] -- EDIT AT YOUR OWN RISK
from CMGTools.RootTools.samples.ComponentCreator import ComponentCreator
import os
kreator = ComponentCreator()
# ------ WZ dataset
WZto3LNu_0 = kreator.makeMCComponentFromLocal("WZto3LNu", "", "/beegfs/data/nanoAODv11/30march2023/MC/2022PostEE/WZto3LNu_TuneCP5_13p6TeV_powheg-pythia8/mcRun3_PostEE_april2023_WZto3LNu_TuneCP5_13p6TeV_powheg-pythia8/230711_162907/0000", ".*root", 5.31)
WZ = [WZto3LNu_0]

# ------ ZZ dataset
ZZto4l_0 = kreator.makeMCComponentFromLocal("ZZto4l", "", "/beegfs/data/nanoAODv11/30march2023/MC/2022PostEE/ZZto4L_TuneCP5_13p6TeV_powheg-pythia8/mcRun3_PostEE_april2023_ZZto4L_TuneCP5_13p6TeV_powheg-pythia8/230626_145402/0000", ".*root", 1.65)
ZZto2L2Q_0 = kreator.makeMCComponentFromLocal("ZZto2L2Q", "", "/beegfs/data/nanoAODv11/30march2023/MC/2022PostEE/ZZto2L2Q_TuneCP5_13p6TeV_powheg-pythia8/mcRun3_PostEE_april2023_ZZto2L2Q_TuneCP5_13p6TeV_powheg-pythia8/230626_145036/0000", ".*root", 8.08)
ZZto2L2Nu_0 = kreator.makeMCComponentFromLocal("ZZto2L2Nu", "", "/beegfs/data/nanoAODv11/30march2023/MC/2022PostEE/ZZto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/mcRun3_PostEE_april2023_ZZto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/230626_144856/0000", ".*root", 1.19)
ZZ = [ZZto4l_0, ZZto2L2Q_0, ZZto2L2Nu_0]

# ------ Tribosons dataset
WWZ_0 = kreator.makeMCComponentFromLocal("WWZ", "", "/beegfs/data/nanoAODv11/30march2023/MC/2022PostEE/WWZ_4F_TuneCP5_13p6TeV_amcatnlo-pythia8/mcRun3_PostEE_april2023_WWZ_4F_TuneCP5_13p6TeV_amcatnlo-pythia8/230614_144831/0000", ".*root", 0.1851)
WZZ_0 = kreator.makeMCComponentFromLocal("WZZ", "", "/beegfs/data/nanoAODv11/30march2023/MC/2022PostEE/WZZ_TuneCP5_13p6TeV_amcatnlo-pythia8/mcRun3_PostEE_april2023_WZZ_TuneCP5_13p6TeV_amcatnlo-pythia8/230614_145019/0000", ".*root", 0.06206)
ZZZ_0 = kreator.makeMCComponentFromLocal("ZZZ", "", "/beegfs/data/nanoAODv11/30march2023/MC/2022PostEE/ZZZ_TuneCP5_13p6TeV_amcatnlo-pythia8/mcRun3_PostEE_april2023_ZZZ_TuneCP5_13p6TeV_amcatnlo-pythia8/230614_144308/0000", ".*root", 0.01591)
WZG_0 = kreator.makeMCComponentFromLocal("WZG", "", "/beegfs/data/nanoAODv11/30march2023/MC/2022PostEE/WZGtoLNuZG_TuneCP5_13p6TeV_amcatnlo-pythia8/mcRun3_PostEE_april2023_WZGtoLNuZG_TuneCP5_13p6TeV_amcatnlo-pythia8/230614_144456/0000", ".*root", 0.08425)
Tribosons = [WWZ_0, WZZ_0, ZZZ_0, WZG_0]

# ------ DY dataset
DYJetsToLL_M_50_0 = kreator.makeMCComponentFromLocal("DYJetsToLL_M_50", "", "/beegfs/data/nanoAODv11/30march2023/MC/2022PostEE/DYto2L-2Jets_MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/mcRun3_PostEE_april2023_DYto2L-2Jets_MLL-50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/230404_142241/0000", ".*root", 6345.99)
DYJetsToLLM10to50_0 = kreator.makeMCComponentFromLocal("DYJetsToLL-M10to50", "", "/beegfs/data/nanoAODv11/30march2023/MC/2022PostEE/DYto2L-2Jets_MLL-10to50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/mcRun3_PostEE_april2023_DYto2L-2Jets_MLL-10to50_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/230404_142007/0000", ".*root", 19982.5)
DY = [DYJetsToLL_M_50_0, DYJetsToLLM10to50_0]

# ------ WJets dataset
WtoLnu_2jets_0 = kreator.makeMCComponentFromLocal("WtoLnu_2jets", "", "/beegfs/data/nanoAODv11/30march2023/MC/2022PostEE/WtoLNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/mcRun3_PostEE_april2023_WtoLNu-2Jets_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/230712_152849/0000", ".*root", 64481.58)
WJets = [WtoLnu_2jets_0]

# ------ ggH dataset
ggHtoZZto4L_0 = kreator.makeMCComponentFromLocal("ggHtoZZto4L", "", "/beegfs/data/nanoAODv11/30march2023/MC/2022PostEE/GluGluHtoZZto4L_M-125_TuneCP5_13p6TeV_powheg2-JHUGenV752-pythia8/mcRun3_PostEE_april2023_GluGluHtoZZto4L_M-125_TuneCP5_13p6TeV_powheg2-JHUGenV752-pythia8/230614_144644/0000", ".*root", 52.276)
ggH = [ggHtoZZto4L_0]

# ------ TT dataset
TTTo2L2Nu_0 = kreator.makeMCComponentFromLocal("TTTo2L2Nu", "", "/beegfs/data/nanoAODv11/30march2023/MC/2022PostEE/TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/mcRun3_PostEE_april2023_TTto2L2Nu_TuneCP5_13p6TeV_powheg-pythia8/230404_141055/0000", ".*root", 97.4488)
TT = [TTTo2L2Nu_0]

# ------ Singletop dataset
TWminus_0 = kreator.makeMCComponentFromLocal("TWminus", "", "/beegfs/data/nanoAODv11/30march2023/MC/2022PostEE/TWminus_DR_AtLeastOneLepton_TuneCP5_13p6TeV_powheg-pythia8/mcRun3_PostEE_april2023_TWminus_DR_AtLeastOneLepton_TuneCP5_13p6TeV_powheg-pythia8/230404_141347/0000", ".*root", 23.8979)
TbarWplus_0 = kreator.makeMCComponentFromLocal("TbarWplus", "", "/beegfs/data/nanoAODv11/30march2023/MC/2022PostEE/TbarWplus_DR_AtLeastOneLepton_TuneCP5_13p6TeV_powheg-pythia8/mcRun3_PostEE_april2023_TbarWplus_DR_AtLeastOneLepton_TuneCP5_13p6TeV_powheg-pythia8/230404_141710/0000", ".*root", 23.8979)
Singletop = [TWminus_0, TbarWplus_0]

# ------ WW dataset
WW_0 = kreator.makeMCComponentFromLocal("WW", "", "/beegfs/data/nanoAODv11/30march2023/MC/2022PostEE/WW_TuneCP5_13p6TeV_pythia8/mcRun3_PostEE_april2023_WW_TuneCP5_13p6TeV_pythia8/230404_142522/0000", ".*root", 116.8)
WW = [WW_0]




mcSamples_list = WZ + ZZ + Tribosons + DY + WJets + ggH + TT + Singletop + WW
mcSamples_toImport = mcSamples_list